title: c0ffee0vrflw.
description: 
author: 
  name: c0ffee0vrflw
  email: v4rd1@protonmail.com
  url: 'https://ashishchaudhary.in/hacker-blog'
baseurl: ''
source: .
destination: ./_site
permalink: '/:title'
paginate: 3
paginate_path: '/page/:num/'
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
owner: c0ffee0vrflw
year: '2021'
url: ''
